application: niv84api
version: 1
runtime: python27
api_version: 1
threadsafe: false
 
handlers:
- url: /static
  static_dir: static
- url: /.*
  script: main.app
  secure: optional

libraries:
- name: lxml
  version: latest
- name: webapp2
  version: latest
- name: jinja2
  version: latest
